#!/usr/bin/env sh

set +e

echo ------------------------------
pwd
echo ------------------------------

while true; do
  nodetool ping
  EXIT_CODE=$?
  if [ $EXIT_CODE -eq 0 ]; then
    echo "Application is up!"
    break
  fi
done

set -e

echo "Running migrations"
#bin/topout_api rpc Elixir.Release.Tasks migrate
echo "Migrations run successfully"
